server:
  port: 7001
eureka:
  instance:
    hostname: kunpeng1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kunpeng2.com:7002/eureka/,http://kunpeng3.com:7003/eureka/

