server:
  port: 7003
eureka:
  instance:
    hostname: kunpeng3.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://kunpeng1.com:7001/eureka/,http://kunpeng2.com:7002/eureka/

